In [3]:
!pip install bs4
from bs4 import BeautifulSoup
import requests
import pandas as pd

Requirement already satisfied: bs4 in c:\users\snata\anaconda3\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\users\snata\anaconda3\lib\site-packages (from bs4) (4.9.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\snata\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.2.1)

Taken a random url from wikipedia that has the necessary data

In [4]:
url="https://en.wikipedia.org/w/index.php?title=List_of_postal_codes_of_Canada:_M&direction=prev&oldid=926287641"

In [5]:
data=requests.get(url).text
soup=BeautifulSoup(data,"html5lib")
tables=soup.find('table')

Create a dataframe to contain the required data.

In [6]:
neighborhood_data = pd.DataFrame(columns=["PostalCode","Borough","Neighborhood"])

lastpostalcode=""
lastborough=""
lastneighborhood=""
for row in soup.find("tbody").find_all("tr"):
    
    col = row.find_all("td")
    
    postalcode=""
    borough=""
    neighborhood=""
    
    #If col is not populated then no need to populate the values in the data frame - so loop back
    if (col == []):
        continue
        
    #Assign the current col values to appropriate variables
    postalcode = col[0].text
    borough = col[1].text.strip()
    neighborhood = col[2].text.strip()

    #If borough is not assigned then no need to populate the values in the data frame - so loop back
    if borough == "Not assigned":
        continue
        
    #If neighborhood is not assigned then populate neighborhood as the borough
    if neighborhood == "Not assigned":
        neighborhood=borough

    #If postal code is same as the last row postal code then combine both neighborhood and continue
    if postalcode == lastpostalcode:
        lastneighborhood = lastneighborhood + ", " + neighborhood
        continue
    
    #No need to write when the first row is being read
    if lastpostalcode=="":
        pass
    #If control reaches here then all values OK and new postal code started - so to be written to the dataframe   
    else:
        neighborhood_data = neighborhood_data.append({"PostalCode":lastpostalcode, "Borough":lastborough, "Neighborhood":lastneighborhood}, ignore_index=True)
        
    #Assign the new values to the last variables
    lastpostalcode=postalcode
    lastborough=borough
    lastneighborhood=neighborhood
pd.set_option('display.max_colwidth',None)    
neighborhood_data

,PostalCode,Borough,Neighborhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Harbourfront, Regent Park"
3,M6A,North York,"Lawrence Heights, Lawrence Manor"
4,M7A,Queen's Park,Queen's Park
...,...,...,...
97,M5X,Downtown Toronto,"First Canadian Place, Underground city"
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern
101,M8Y,Etobicoke,"Humber Bay, King's Mill Park, Kingsway Park South East, Mimico NE, Old Mill South, The Queensway East, Royal York South East, Sunnylea"

In [8]:
neighborhood_data.shape

(102, 3)

In [ ]:
!pip install wheel
!pip install pipwin

!pipwin install numpy
!pipwin install pandas
!pipwin install shapely
!pipwin install gdal
!pipwin install fiona
!pipwin install pyproj
!pipwin install six
!pipwin install rtree
!pipwin install geopandas
#!pip uninstall geopy
import geocoder # import geocoder

In [ ]:
# initialize your variable to None
lat_lng_coords = None
print("hello222")
# loop until you get the coordinates
while(lat_lng_coords is None):
    g = geocoder.google('{}, Toronto, Ontario'.format(postal_code))
    lat_lng_coords = g.latlng
    print("hello11")

print("hello")
latitude = lat_lng_coords[0]
print(latitude)
longitude = lat_lng_coords[1]

Import geocode.csv in to dataframe

In [9]:
df_geocode=pd.read_csv('Geospatial_Coordinates.csv')
df_geocode.head(15)

   Postal Code   Latitude  Longitude
0          M1B  43.806686 -79.194353
1          M1C  43.784535 -79.160497
2          M1E  43.763573 -79.188711
3          M1G  43.770992 -79.216917
4          M1H  43.773136 -79.239476
5          M1J  43.744734 -79.239476
6          M1K  43.727929 -79.262029
7          M1L  43.711112 -79.284577
8          M1M  43.716316 -79.239476
9          M1N  43.692657 -79.264848
10         M1P  43.757410 -79.273304
11         M1R  43.750071 -79.295849
12         M1S  43.794200 -79.262029
13         M1T  43.781638 -79.304302
14         M1V  43.815252 -79.284577

Rename the Postal Code column in geocode dataframe to match that of neighborhood dataframe

In [28]:
df_geocode.rename(columns={'Postal Code': 'PostalCode'}, inplace=True)

In [33]:
df_geocode.head(10)

  PostalCode   Latitude  Longitude
0        M1B  43.806686 -79.194353
1        M1C  43.784535 -79.160497
2        M1E  43.763573 -79.188711
3        M1G  43.770992 -79.216917
4        M1H  43.773136 -79.239476
5        M1J  43.744734 -79.239476
6        M1K  43.727929 -79.262029
7        M1L  43.711112 -79.284577
8        M1M  43.716316 -79.239476
9        M1N  43.692657 -79.264848

Merge the 2 dataframes to get the desired result

In [30]:
neighborhood_data.merge(df_geocode, how='left')

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Harbourfront, Regent Park",43.654260,-79.360636
3,M6A,North York,"Lawrence Heights, Lawrence Manor",43.718518,-79.464763
4,M7A,Queen's Park,Queen's Park,43.662301,-79.389494
...,...,...,...,...,...
97,M5X,Downtown Toronto,"First Canadian Place, Underground city",43.648429,-79.382280
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",43.653654,-79.506944
99,M4Y,Downtown Toronto,Church and Wellesley,43.665860,-79.383160
100,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern,43.662744,-79.321558
101,M8Y,Etobicoke,"Humber Bay, King's Mill Park, Kingsway Park South East, Mimico NE, Old Mill South, The Queensway East, Royal York South East, Sunnylea",43.636258,-79.498509